### ISSUE TITLE
host.readDirectory error while using inspectWithPreamble

### ISSUE THREAD

**Issue by vlasy** [grissius/intspector#1]
I wanted to use this wonderful tool while updating tests on [cosmas](https://github.com/AckeeCZ/cosmas) but I encountered a rather annoying error while  using `inspectWithPreamble` function.

Code:

```
console.log(inspectWithPreamble(`
import loggerFactory from 'cosmas';
const logger = loggerFactory('a');`)('typeof logger'));
```

And after running `jest` tests, the error is following:

```
TypeError: host.readDirectory is not a function

      17 |     console.log(inspectWithPreamble(`
      18 |     import loggerFactory from '..';
    > 19 |     const logger = loggerFactory('a');`)('typeof logger'));
         |                                         ^
      20 |     expect(logger).toBeDefined();
      21 | });
      22 |

      at getFileNamesFromConfigSpecs (node_modules/typescript/lib/typescript.js:26140:40)
      at matchFileNames (node_modules/typescript/lib/typescript.js:26060:16)
      at getFileNames (node_modules/typescript/lib/typescript.js:25628:26)
      at parseJsonConfigFileContentWorker (node_modules/typescript/lib/typescript.js:25561:18)
      at Object.parseJsonConfigFileContent (node_modules/typescript/lib/typescript.js:25510:16)
      at convertConfigToCompilerOptions (node_modules/intspector/src/lib/options.ts:14:11)
      at Object.<anonymous>.exports.setOptions (node_modules/intspector/src/lib/options.ts:57:26)
      at Object.<anonymous>.exports.getOptions (node_modules/intspector/src/lib/options.ts:73:9)
      at Object.<anonymous>.exports.createInlineProgram (node_modules/intspector/src/lib/program.ts:32:21)
      at node_modules/intspector/src/lib/inspect.ts:34:11
      at Object.<anonymous> (src/tests/create.test.ts:19:41)
```

Versions used:
intspector: 1.0.1
typescript: 3.5.3
jest: 24.1.0

Thanks for help 🙏

**Comment by smolijar** [comment]
This has been discussed in Microsoft/TypeScript#5276, but without working solution for TS 3.6. It is required to send an instance. `ts.sys` provides required interface. c0a586a6763c22668466fb6478e8c80b128ace34
